
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
          node-version: 14

    - name: Remove package-lock.json
      uses: JesseTG/rm@v1.0.2
      with:
        path: package-lock.json          

    - name: Install Packages
      run: npm install # Install Dependencies

    - name: Create env file
      run: |
        touch .env
        echo API_KEY=${{ secrets.API_KEY }} >> .env
        cat .env 

    - name: Build
      run: npm run build    

    - name: Install Surge
      run: npm install -g surge

    - name: Deploy to Surge
      run:  surge ./dist ramadan-time.surge.sh --token ${{secrets.SURGE_TOKEN}}